name: mojodex_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.4.10+58

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  colorful_safe_area: ^1.0.0
  logging: ^1.2.0
  http: ^1.1.0
  lazy_load_scrollview: ^1.3.0
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  provider: ^6.0.5
  skeletons: ^0.0.3
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1
  loading_animation_widget: ^1.2.0+4
  audio_waveforms: ^1.0.4
  path_provider: ^2.1.2
  socket_io_client: ^2.0.3+1
  wakelock_plus: ^1.1.3
  permission_handler: ^11.0.1
  timelines: ^0.1.0
  dio: ^5.3.3
  easy_localization: ^3.0.3
  webview_flutter: ^4.4.1
  cached_network_image: ^3.3.0
  animated_snack_bar: ^0.3.1
  mailto: ^2.0.0
  url_launcher: ^6.1.14
  flutter_local_notifications: ^16.1.0
  firebase_core: ^2.19.0
  firebase_messaging: ^14.7.1
  badges: ^3.1.2
  in_app_purchase: ^3.1.11
  collection: ^1.17.2
  flutter_slidable: ^3.0.1
  go_router: ^13.0.1
  google_sign_in: ^6.2.1
  device_calendar:
    git:
      url: https://github.com/builttoroam/device_calendar.git
      ref: develop

dev_dependencies:
  flutter_native_splash:
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/images/
    - lib/DS/icons/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: lib/DS/fonts/HelveticaNeue.otf
    - family: HankenGrotesk
      fonts:
        - asset: lib/DS/fonts/HankenGrotesk-Regular.ttf
